pipeline {
	agent {
        label 'AGENT-1'
    }
    environment {
        appVersion = ''
        REGION = 'us-east-1'
        ACC_ID = '009160060207'
        PROJECT = 'roboshop'
        CLUSTER  = 'roboshop-dev'
    }
    options {
        timeout(time: 20, unit: 'MINUTES') 
        disableConcurrentBuilds()
        ansiColor('xterm')
    } 
    /* parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')

        text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')

        booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')

        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')

        password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
    } */
	stages {
        stage('init'){
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                            sh """
                                cd 60-eks
                                terraform init -reconfigure -upgrade
                            """
                        }
                    }
                }
            }
        stage('Import Cluster If Exists') {
            steps {
                dir("60-eks") {
                    withAWS(credentials: 'aws-creds', region: "${REGION}") {
                        sh """
                          aws eks describe-cluster --name ${CLUSTER} --region ${REGION} >/dev/null 2>&1 && \
                          (terraform state list | grep 'module.eks.aws_eks_cluster.this' || terraform import module.eks.aws_eks_cluster.this[0] ${CLUSTER}) || \
                          echo "ℹ️ Cluster ${CLUSTER} not found. Terraform will create it."
                        """
                        // Refresh state after import so Terraform doesn’t try to re-create the cluster
                        sh "terraform plan -refresh-only -no-color"
                    }
                }
            }
        }

        stage('plan'){
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                            sh """
                                cd 60-eks
                                terraform plan
                            """
                        }
                    }
                }
            }
        stage('apply'){
            // input {
            //     message "Should we continue?"
            //     ok "Yes, we should."
            //     submitter "alice,bob"
            // }
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                            sh """
                                cd 60-eks
                                terraform apply -auto-approve
                            """
                        }
                    }
                }
            }
    }
	
    post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir()
        }
        success { 
            echo 'I will always say success!'
        }
        failure { 
            echo 'I will always say failure!'
        }
    }
} 